include: "rules/common.smk"
include: "rules/download_image.smk"
include: "rules/generate_metadata.smk"
include: "rules/crop_image.smk"
include: "rules/segment_image.smk"
include: "rules/create_morphological_analysis.smk"

rule all:
    input:
        get_morphology_files
