include: "rules/common.smk"
include: "rules/download_image.smk"
include: "rules/generate_metadata.smk"
include: "rules/transform_metadata.smk"
include: "rules/crop_image.smk"
include: "rules/segment_image.smk"

rule all:
    input:
        get_segmentation_files
